version: 2
updates:
  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: daily
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
  - package-ecosystem: npm
    directory: /vs-ui
    schedule:
      interval: daily
