name: Deploy Docker

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v3.5.1
        with:
          java-version: 11
          distribution: 'zulu'
      - name: Cache Java Dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-build-${{ hashFiles('*.gradle') }}
      - name: Docker Login
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u nickrobisonusds --password-stdin
      - name: Build and Push Docker
        run: ./gradlew jib

