name: Test

# Run this on pushes to any branch that change a backend file or the workflow definition
on:
  workflow_dispatch: # because sometimes you just want to force a branch to have tests run
  pull_request:
    branches:
      - "**"
  push:
    branches:
      - main
env:
  JAVA_VERSION: 15
  NODE_VERSION: 14

jobs:
  backend:
    runs-on: ubuntu-latest
    services:
      test-db:
        image: postgis/postgis:13-3.1-alpine
        env:
          POSTGRES_PASSWORD: this_is_not_safe
          POSTGRES_DB: vs
          # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Disable shallow clones so Sonar can have all the data
      - name: Set up JDK ${{env.JAVA_VERSION}}
        uses: actions/setup-java@v2
        with:
          java-version: ${{env.JAVA_VERSION}}
          distribution: 'zulu'
      - name: Cache Sonar Dependencies
        uses: actions/cache@v2
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Java Dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ hashFiles('*.gradle') }}
      - name: Run Java Tests
        env:
          SPRING_PROFILES_ACTIVE: ci
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew test jacocoTestReport sonarqube --info
      - name: Archive Test Results
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: test-report
          path: api-application/build/test-results/test
          retention-days: 7
  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{env.NODE_VERSION}}
        uses: actions/setup-node@v2.1.5
        with:
          node-version: ${{env.NODE_VERSION}}
      - name: Cache npm local files
        uses: actions/cache@v2
        with:
          path: |
            ./vs-ui/node_modules
          key: npm-${{env.NODE_VERSION}}-${{ hashFiles('vs-ui/yarn.lock', 'vs-ui/package.json') }}
      - name: Node setup
        working-directory: ./vs-ui
        run: yarn
      - name: Lint front-end
        working-directory: ./vs-ui
        run: yarn lint
      - name: Frontend tests
        working-directory: ./vs-ui
        run: yarn test
      - name: Build release
        working-directory: ./vs-ui
        run: yarn build

